/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResumeMatchRouteImport } from './routes/resume-match'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ApplyRouteImport } from './routes/apply.'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeMatchRoute = ResumeMatchRouteImport.update({
  id: '/resume-match',
  path: '/resume-match',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply/',
  path: '/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRoute
  '/profile': typeof ProfileRoute
  '/resume-match': typeof ResumeMatchRoute
  '/saved': typeof SavedRoute
  '/apply/': typeof ApplyRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRoute
  '/profile': typeof ProfileRoute
  '/resume-match': typeof ResumeMatchRoute
  '/saved': typeof SavedRoute
  '/apply': typeof ApplyRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRoute
  '/profile': typeof ProfileRoute
  '/resume-match': typeof ResumeMatchRoute
  '/saved': typeof SavedRoute
  '/apply/': typeof ApplyRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/dashboard'
    | '/employer'
    | '/profile'
    | '/resume-match'
    | '/saved'
    | '/apply/'
    | '/jobs/$jobId'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/dashboard'
    | '/employer'
    | '/profile'
    | '/resume-match'
    | '/saved'
    | '/apply'
    | '/jobs/$jobId'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/dashboard'
    | '/employer'
    | '/profile'
    | '/resume-match'
    | '/saved'
    | '/apply/'
    | '/jobs/$jobId'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  DashboardRoute: typeof DashboardRoute
  EmployerRoute: typeof EmployerRoute
  ProfileRoute: typeof ProfileRoute
  ResumeMatchRoute: typeof ResumeMatchRoute
  SavedRoute: typeof SavedRoute
  ApplyRoute: typeof ApplyRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-match': {
      id: '/resume-match'
      path: '/resume-match'
      fullPath: '/resume-match'
      preLoaderRoute: typeof ResumeMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/apply'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  DashboardRoute: DashboardRoute,
  EmployerRoute: EmployerRoute,
  ProfileRoute: ProfileRoute,
  ResumeMatchRoute: ResumeMatchRoute,
  SavedRoute: SavedRoute,
  ApplyRoute: ApplyRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
